In [1]:
#importing Libraries

import numpy as np
import pandas as pd

# Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

#Searching text patterns
import re

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [5]:
import pandas as pd

#Loading the Dataset

# The original URL points to the GitHub webpage for the CSV, not the raw data.
# This causes a ParserError because pandas tries to read HTML as CSV.
# We need to change 'blob' to 'raw' and the domain to 'raw.githubusercontent.com' to get the raw CSV data.
url=('https://raw.githubusercontent.com/hiteshchoudhary200218-gif/Factory-to-Customer-Shipping-Route-Efficiency-Analysis-for-Nassau-Candy-Distributor/main/Raw%20Dataset.csv')

df=pd.read_csv(url)

In [ ]:
#To view the data:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
# Shape of dataset
df.shape

(10194, 18)

In [ ]:
# Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

In [ ]:
# Statistical Summary
df.describe()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,134468.961154,13.908537,3.791838,9.166451,4.742087
std,2942.898656,20231.483007,11.341020,2.228317,6.643740,5.061647
min,1.000000,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,192314.000000,260.000000,14.000000,130.000000,130.000000

In [ ]:
# Column Names
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost'],
      dtype='object')

In [ ]:
#View first 5 rows
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
#View last 5 rows
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
10189,10190,US-2024-143259-CHO-MIL-31000,30-12-2025,26-06-2030,Standard Class,143259,United States,New York City,New York,10009,Chocolate,Atlantic,CHO-MIL-31000,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42
10190,10191,US-2024-115427-CHO-NUT-13000,30-12-2025,26-06-2030,Standard Class,115427,United States,Fairfield,California,94533,Chocolate,Pacific,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,6.98,2,4.98,2.00
10191,10192,US-2024-156720-CHO-SCR-58000,30-12-2025,26-06-2030,Standard Class,156720,United States,Loveland,Colorado,80538,Chocolate,Pacific,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
10192,10193,US-2024-143259-CHO-TRI-54000,30-12-2025,26-06-2030,Standard Class,143259,United States,New York City,New York,10009,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,26.25,7,17.15,9.10
10193,10194,CA-2024-143500-CHO-SCR-58000,30-12-2025,26-06-2030,Standard Class,143500,Canada,Charlottetown,Prince Edward Island,C0A,Chocolate,Atlantic,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30

In [ ]:
#Check Null Values
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [ ]:
#Check Duplicate Records
df.duplicated().sum()

np.int64(0)

**Step 1: Data Cleaning**

In [ ]:
#Convert Dates

df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d-%m-%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d-%m-%Y')

In [ ]:
#Calculate Lead Time

df['Lead_Time'] = (
    df['Ship Date'] - df['Order Date']
).dt.days

In [ ]:
#Remove Invalid Records

df = df[df['Lead_Time'] >= 0]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
 18  Lead_Time       10194 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(4), object(10)
memory usage: 1.5+ MB

**Step 2: Factory Mapping**

In [ ]:
factory_map = {
    "Wonka Bar - Nutty Crunch Surprise":"Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows":"Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious":"Lot's O' Nuts",

    "Wonka Bar - Milk Chocolate":"Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel":"Wicked Choccy's",

    "Laffy Taffy":"Sugar Shack",
    "SweeTARTS":"Sugar Shack",
    "Nerds":"Sugar Shack",
    "Fun Dip":"Sugar Shack",
    "Fizzy Lifting Drinks":"Sugar Shack"
}

In [ ]:
df["Factory"] = df["Product Name"].map(factory_map)

**Step 3: Route Definition**

In [ ]:
#Route by State

df["Route_State"] = (
    df["Factory"] + " → " +
    df["State/Province"]
)

In [ ]:
#Route by Region

df["Route_Region"] = (
    df["Factory"] + " → " +
    df["Region"]
)

In [ ]:
# KPI 1 - Total Shipments

len(df)

10194

In [ ]:
#KPI 2 - Average Lead Time

df["Lead_Time"].mean()

np.float64(1320.8418677653522)

In [ ]:
#KPI 3 - Total Sales

df["Sales"].sum()

np.float64(141783.63)

In [ ]:
#KPI 4 - Gross Profit

df["Gross Profit"].sum()

np.float64(93442.8)

In [ ]:
#KPI 5 - Delay Frequency
#Threshold = 5 Days

(
(df["Lead_Time"] > 5).mean()
)*100

np.float64(100.0)

In [ ]:
#Route Performance Table

route_perf = (
    df.groupby("Route_State")
    .agg({
        "Lead_Time":["mean","std","count"]
    })
)

In [ ]:
#Top 10 Efficient Routes

route_perf.sort_values(
    ('Lead_Time','mean')
).head(10)

                                             Lead_Time
                                                  mean         std count
Route_State
Wicked Choccy's → Maine                     908.000000    0.000000     2
Sugar Shack → Delaware                      910.000000         NaN     1
Sugar Shack → Florida                      1031.000000  211.310199     3
Sugar Shack → Illinois                     1089.000000  257.386868     2
Wicked Choccy's → South Dakota             1152.000000  422.620397     3
Wicked Choccy's → Nevada                   1182.250000  226.373033    12
Lot's O' Nuts → Maine                      1213.500000  149.664625     6
Lot's O' Nuts → Newfoundland and Labrador  1216.166667  357.447292     6
Wicked Choccy's → Montana                  1221.857143  389.897606     7
Lot's O' Nuts → Virginia                   1229.486239  262.008609   109

In [ ]:
#Bottom 10 Inefficient Routes

route_perf.sort_values(
    ('Lead_Time','mean'),
    ascending=False
).head(10)

                                Lead_Time
                                     mean         std count
Route_State
Sugar Shack → New Jersey           1642.0         NaN     1
Sugar Shack → Connecticut          1641.0         NaN     1
Wicked Choccy's → West Virginia    1639.0    0.000000     2
Lot's O' Nuts → North Dakota       1638.2    1.643168     5
Sugar Shack → Washington           1638.0         NaN     1
Sugar Shack → California           1638.0         NaN     1
Sugar Shack → Ohio                 1637.5    3.535534     2
Wicked Choccy's → North Dakota     1637.0    0.000000     2
Lot's O' Nuts → West Virginia      1637.0    2.828427     2
Lot's O' Nuts → Vermont            1492.4  200.285546     5

In [ ]:
#State-Level Delays

state_delay = (
    df.groupby("State/Province")
    ["Lead_Time"]
    .mean()
)

In [ ]:
#Region Performance

region_perf = (
    df.groupby("Region")
    ["Lead_Time"]
    .mean()
)

In [ ]:
#Average Lead Time by Ship Mode

df.groupby("Ship Mode")["Lead_Time"].mean()

Ship Mode
First Class       1338.275840
Same Day          1333.442413
Second Class      1323.845376
Standard Class    1314.334641
Name: Lead_Time, dtype: float64

In [ ]:
#Ship Mode vs Profit

df.groupby("Ship Mode").agg({
    "Sales":"sum",
    "Gross Profit":"sum",
    "Lead_Time":"mean"
})

                   Sales  Gross Profit    Lead_Time
Ship Mode
First Class     21319.39      14011.09  1338.275840
Same Day         7113.67       4700.73  1333.442413
Second Class    27860.22      18306.52  1323.845376
Standard Class  85490.35      56424.46  1314.334641

In [ ]:
#Normalize Lead Time

max_lead_time = df['Lead_Time'].max()
df['Efficiency_Score'] = 100 - (df['Lead_Time'] / max_lead_time) * 100

In [ ]:
max_time = df["Lead_Time"].max()

df["Efficiency_Score"] = (
100 -
(df["Lead_Time"]/max_time)*100
)

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Product Name,Sales,Units,Gross Profit,Cost,Lead_Time,Factory,Route_State,Route_Region,Efficiency_Score
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909,Wicked Choccy's,Wicked Choccy's → Texas,Wicked Choccy's → Interior,44.640682
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909,Wicked Choccy's,Wicked Choccy's → Illinois,Wicked Choccy's → Interior,44.640682
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior,44.640682
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior,44.640682
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912,Wicked Choccy's,Wicked Choccy's → Pennsylvania,Wicked Choccy's → Atlantic,44.457978

In [ ]:
df["Lead_Time"].dtype

dtype('int64')

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Product Name,Sales,Units,Gross Profit,Cost,Lead_Time,Factory,Route_State,Route_Region,Efficiency_Score
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909,Wicked Choccy's,Wicked Choccy's → Texas,Wicked Choccy's → Interior,44.640682
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909,Wicked Choccy's,Wicked Choccy's → Illinois,Wicked Choccy's → Interior,44.640682
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior,44.640682
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior,44.640682
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912,Wicked Choccy's,Wicked Choccy's → Pennsylvania,Wicked Choccy's → Atlantic,44.457978

In [ ]:
df.to_csv("Raw Dataset.csv", index=False)

In [6]:
print(df['Order Date'].head(10))
print(df['Ship Date'].head(10))
print(df['Order Date'].dtype)

0    2024-01-03
1    2024-01-04
2    2024-01-04
3    2024-01-04
4    2024-01-05
5    2024-01-06
6    2024-01-06
7    2024-01-06
8    2024-01-06
9    2024-01-06
Name: Order Date, dtype: object
0    2026-06-30
1    2026-07-01
2    2026-07-01
3    2026-07-01
4    2026-07-05
5    2026-07-03
6    2026-07-03
7    2026-06-30
8    2026-07-03
9    2026-07-03
Name: Ship Date, dtype: object
object

In [8]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%Y-%m-%d')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%Y-%m-%d')

print(df[['Order Date', 'Ship Date']].head())

  Order Date  Ship Date
0 2024-01-03 2026-06-30
1 2024-01-04 2026-07-01
2 2024-01-04 2026-07-01
3 2024-01-04 2026-07-01
4 2024-01-05 2026-07-05

In [9]:
df['Lead Time (days)'] = (df['Ship Date'] - df['Order Date']).dt.days

print(df['Lead Time (days)'].describe())

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead Time (days), dtype: float64

In [10]:
print(df['Lead Time (days)'].describe())
print()
print("Negative lead times:", (df['Lead Time (days)'] < 0).sum())
print("Lead times over 30 days:", (df['Lead Time (days)'] > 30).sum())

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead Time (days), dtype: float64

Negative lead times: 0
Lead times over 30 days: 10194

In [11]:
product_to_factory = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",
    "Everlasting Gobstopper": "Secret Factory",
    "Hair Toffee": "The Other Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",
    "Kazookles": "The Other Factory"
}

df['Factory'] = df['Product Name'].map(product_to_factory)

print(df['Factory'].value_counts())
print()
print("Unmapped products (should be empty):")
print(df[df['Factory'].isnull()]['Product Name'].unique())

Factory
Lot's O' Nuts        5692
Wicked Choccy's      4152
Secret Factory        217
The Other Factory     100
Sugar Shack            33
Name: count, dtype: int64

Unmapped products (should be empty):
[]

In [12]:
df['Route_State'] = df['Factory'] + " → " + df['State/Province']
df['Route_Region'] = df['Factory'] + " → " + df['Region']

print(df[['Factory', 'State/Province', 'Route_State']].head())

           Factory State/Province                     Route_State
0  Wicked Choccy's          Texas         Wicked Choccy's → Texas
1  Wicked Choccy's       Illinois      Wicked Choccy's → Illinois
2    Lot's O' Nuts       Illinois        Lot's O' Nuts → Illinois
3    Lot's O' Nuts       Illinois        Lot's O' Nuts → Illinois
4  Wicked Choccy's   Pennsylvania  Wicked Choccy's → Pennsylvania

In [13]:
route_state_summary = df.groupby('Route_State').agg(
    Total_Shipments=('Order ID', 'count'),
    Avg_Lead_Time=('Lead Time (days)', 'mean'),
    Lead_Time_StdDev=('Lead Time (days)', 'std'),
    Min_Lead_Time=('Lead Time (days)', 'min'),
    Max_Lead_Time=('Lead Time (days)', 'max')
).reset_index()

route_state_summary['Avg_Lead_Time'] = route_state_summary['Avg_Lead_Time'].round(2)
route_state_summary['Lead_Time_StdDev'] = route_state_summary['Lead_Time_StdDev'].round(2)

print(route_state_summary.sort_values('Avg_Lead_Time').head(10))

                         Route_State  Total_Shipments  Avg_Lead_Time  \
80       Secret Factory → New Mexico                2          906.0
76         Secret Factory → Nebraska                1          906.0
121    The Other Factory → Louisiana                1          907.0
115  The Other Factory → Connecticut                2          907.5
75      Secret Factory → Mississippi                1          908.0
158          Wicked Choccy's → Maine                2          908.0
70        Secret Factory → Louisiana                2          908.5
64         Secret Factory → Delaware                1          909.0
88   Secret Factory → South Carolina                1          909.0
74        Secret Factory → Minnesota                1          909.0

     Lead_Time_StdDev  Min_Lead_Time  Max_Lead_Time
80               2.83            904            908
76                NaN            906            906
121               NaN            907            907
115              2.12            906            909
75                NaN            908            908
158              0.00            908            908
70               0.71            908            909
64                NaN            909            909
88                NaN            909            909
74                NaN            909            909

In [14]:
route_region_summary = df.groupby('Route_Region').agg(
    Total_Shipments=('Order ID', 'count'),
    Avg_Lead_Time=('Lead Time (days)', 'mean'),
    Lead_Time_StdDev=('Lead Time (days)', 'std')
).reset_index()

route_region_summary['Avg_Lead_Time'] = route_region_summary['Avg_Lead_Time'].round(2)
route_region_summary['Lead_Time_StdDev'] = route_region_summary['Lead_Time_StdDev'].round(2)

print(route_region_summary.sort_values('Avg_Lead_Time'))

                    Route_Region  Total_Shipments  Avg_Lead_Time  \
9             Sugar Shack → Gulf                4        1091.25
14  The Other Factory → Interior               11        1206.64
13      The Other Factory → Gulf               19        1272.63
12  The Other Factory → Atlantic               38        1282.74
6      Secret Factory → Interior               45        1289.09
15   The Other Factory → Pacific               32        1307.22
7       Secret Factory → Pacific               63        1307.73
17        Wicked Choccy's → Gulf              663        1309.11
1           Lot's O' Nuts → Gulf              897        1313.98
16    Wicked Choccy's → Atlantic             1197        1315.97
3        Lot's O' Nuts → Pacific             1813        1317.53
10        Sugar Shack → Interior                8        1318.62
2       Lot's O' Nuts → Interior             1321        1324.20
18    Wicked Choccy's → Interior              950        1324.55
0       Lot's O' Nuts → Atlantic             1661        1326.83
19     Wicked Choccy's → Pacific             1342        1329.10
5          Secret Factory → Gulf               37        1332.54
4      Secret Factory → Atlantic               72        1349.25
8         Sugar Shack → Atlantic               18        1375.39
11         Sugar Shack → Pacific                3        1516.67

    Lead_Time_StdDev
9             210.45
14            274.43
13            272.73
12            262.17
6             311.23
15            251.42
7             276.18
17            259.90
1             266.59
16            255.39
3             266.67
10            235.26
2             258.41
18            266.33
0             255.99
19            266.22
5             304.83
4             280.72
8             274.61
11            210.16

In [15]:
print("TOP 10 MOST EFFICIENT ROUTES (lowest avg lead time):")
print(route_state_summary.sort_values('Avg_Lead_Time').head(10))

print("\nBOTTOM 10 LEAST EFFICIENT ROUTES (highest avg lead time):")
print(route_state_summary.sort_values('Avg_Lead_Time', ascending=False).head(10))

TOP 10 MOST EFFICIENT ROUTES (lowest avg lead time):
                         Route_State  Total_Shipments  Avg_Lead_Time  \
80       Secret Factory → New Mexico                2          906.0
76         Secret Factory → Nebraska                1          906.0
121    The Other Factory → Louisiana                1          907.0
115  The Other Factory → Connecticut                2          907.5
75      Secret Factory → Mississippi                1          908.0
158          Wicked Choccy's → Maine                2          908.0
70        Secret Factory → Louisiana                2          908.5
64         Secret Factory → Delaware                1          909.0
88   Secret Factory → South Carolina                1          909.0
74        Secret Factory → Minnesota                1          909.0

     Lead_Time_StdDev  Min_Lead_Time  Max_Lead_Time
80               2.83            904            908
76                NaN            906            906
121               NaN            907            907
115              2.12            906            909
75                NaN            908            908
158              0.00            908            908
70               0.71            908            909
64                NaN            909            909
88                NaN            909            909
74                NaN            909            909

BOTTOM 10 LEAST EFFICIENT ROUTES (highest avg lead time):
                         Route_State  Total_Shipments  Avg_Lead_Time  \
103         Sugar Shack → New Jersey                1         1642.0
78    Secret Factory → New Hampshire                1         1641.0
98         Sugar Shack → Connecticut                1         1641.0
194  Wicked Choccy's → West Virginia                2         1639.0
37      Lot's O' Nuts → North Dakota                5         1638.2
97          Sugar Shack → California                1         1638.0
125       The Other Factory → Nevada                1         1638.0
110         Sugar Shack → Washington                1         1638.0
63      Secret Factory → Connecticut                1         1638.0
105               Sugar Shack → Ohio                2         1637.5

     Lead_Time_StdDev  Min_Lead_Time  Max_Lead_Time
103               NaN           1642           1642
78                NaN           1641           1641
98                NaN           1641           1641
194              0.00           1639           1639
37               1.64           1637           1640
97                NaN           1638           1638
125               NaN           1638           1638
110               NaN           1638           1638
63                NaN           1638           1638
105              3.54           1635           1640

In [16]:
print("TOP 10 MOST EFFICIENT ROUTES (lowest avg lead time):")
print(route_state_summary.sort_values('Avg_Lead_Time').head(10))

print("\nBOTTOM 10 LEAST EFFICIENT ROUTES (highest avg lead time):")
print(route_state_summary.sort_values('Avg_Lead_Time', ascending=False).head(10))

TOP 10 MOST EFFICIENT ROUTES (lowest avg lead time):
                         Route_State  Total_Shipments  Avg_Lead_Time  \
80       Secret Factory → New Mexico                2          906.0
76         Secret Factory → Nebraska                1          906.0
121    The Other Factory → Louisiana                1          907.0
115  The Other Factory → Connecticut                2          907.5
75      Secret Factory → Mississippi                1          908.0
158          Wicked Choccy's → Maine                2          908.0
70        Secret Factory → Louisiana                2          908.5
64         Secret Factory → Delaware                1          909.0
88   Secret Factory → South Carolina                1          909.0
74        Secret Factory → Minnesota                1          909.0

     Lead_Time_StdDev  Min_Lead_Time  Max_Lead_Time
80               2.83            904            908
76                NaN            906            906
121               NaN            907            907
115              2.12            906            909
75                NaN            908            908
158              0.00            908            908
70               0.71            908            909
64                NaN            909            909
88                NaN            909            909
74                NaN            909            909

BOTTOM 10 LEAST EFFICIENT ROUTES (highest avg lead time):
                         Route_State  Total_Shipments  Avg_Lead_Time  \
103         Sugar Shack → New Jersey                1         1642.0
78    Secret Factory → New Hampshire                1         1641.0
98         Sugar Shack → Connecticut                1         1641.0
194  Wicked Choccy's → West Virginia                2         1639.0
37      Lot's O' Nuts → North Dakota                5         1638.2
97          Sugar Shack → California                1         1638.0
125       The Other Factory → Nevada                1         1638.0
110         Sugar Shack → Washington                1         1638.0
63      Secret Factory → Connecticut                1         1638.0
105               Sugar Shack → Ohio                2         1637.5

     Lead_Time_StdDev  Min_Lead_Time  Max_Lead_Time
103               NaN           1642           1642
78                NaN           1641           1641
98                NaN           1641           1641
194              0.00           1639           1639
37               1.64           1637           1640
97                NaN           1638           1638
125               NaN           1638           1638
110               NaN           1638           1638
63                NaN           1638           1638
105              3.54           1635           1640

In [17]:
print(df['Ship Mode'].value_counts())

Ship Mode
Standard Class    6120
Second Class      1979
First Class       1548
Same Day           547
Name: count, dtype: int64

In [18]:
shipmode_summary = df.groupby('Ship Mode').agg(
    Total_Shipments=('Order ID', 'count'),
    Avg_Lead_Time=('Lead Time (days)', 'mean'),
    Lead_Time_StdDev=('Lead Time (days)', 'std')
).reset_index()

shipmode_summary['Avg_Lead_Time'] = shipmode_summary['Avg_Lead_Time'].round(2)
shipmode_summary['Lead_Time_StdDev'] = shipmode_summary['Lead_Time_StdDev'].round(2)

print(shipmode_summary.sort_values('Avg_Lead_Time'))

        Ship Mode  Total_Shipments  Avg_Lead_Time  Lead_Time_StdDev
3  Standard Class             6120        1314.33            262.40
2    Second Class             1979        1323.85            261.81
1        Same Day              547        1333.44            253.81
0     First Class             1548        1338.28            265.63

In [19]:
delay_threshold = 7  # days

df['Is_Delayed'] = df['Lead Time (days)'] > delay_threshold

delay_by_route = df.groupby('Route_State').agg(
    Total_Shipments=('Order ID', 'count'),
    Delayed_Shipments=('Is_Delayed', 'sum')
).reset_index()

delay_by_route['Delay_Rate (%)'] = (delay_by_route['Delayed_Shipments'] / delay_by_route['Total_Shipments'] * 100).round(2)

print(delay_by_route.sort_values('Delay_Rate (%)', ascending=False).head(10))

                            Route_State  Total_Shipments  Delayed_Shipments  \
0               Lot's O' Nuts → Alabama               34                 34
1               Lot's O' Nuts → Alberta               16                 16
2               Lot's O' Nuts → Arizona              111                111
3              Lot's O' Nuts → Arkansas               31                 31
4      Lot's O' Nuts → British Columbia               18                 18
5            Lot's O' Nuts → California             1125               1125
6              Lot's O' Nuts → Colorado              103                103
7           Lot's O' Nuts → Connecticut               47                 47
8              Lot's O' Nuts → Delaware               43                 43
9  Lot's O' Nuts → District of Columbia                8                  8

   Delay_Rate (%)
0           100.0
1           100.0
2           100.0
3           100.0
4           100.0
5           100.0
6           100.0
7           100.0
8           100.0
9           100.0

In [20]:
min_lead = route_state_summary['Avg_Lead_Time'].min()
max_lead = route_state_summary['Avg_Lead_Time'].max()

route_state_summary['Efficiency_Score'] = (
    100 * (max_lead - route_state_summary['Avg_Lead_Time']) / (max_lead - min_lead)
).round(1)

print(route_state_summary.sort_values('Efficiency_Score', ascending=False).head(10))

                         Route_State  Total_Shipments  Avg_Lead_Time  \
76         Secret Factory → Nebraska                1          906.0
80       Secret Factory → New Mexico                2          906.0
121    The Other Factory → Louisiana                1          907.0
115  The Other Factory → Connecticut                2          907.5
75      Secret Factory → Mississippi                1          908.0
158          Wicked Choccy's → Maine                2          908.0
70        Secret Factory → Louisiana                2          908.5
74        Secret Factory → Minnesota                1          909.0
64         Secret Factory → Delaware                1          909.0
88   Secret Factory → South Carolina                1          909.0

     Lead_Time_StdDev  Min_Lead_Time  Max_Lead_Time  Efficiency_Score
76                NaN            906            906             100.0
80               2.83            904            908             100.0
121               NaN            907            907              99.9
115              2.12            906            909              99.8
75                NaN            908            908              99.7
158              0.00            908            908              99.7
70               0.71            908            909              99.7
74                NaN            909            909              99.6
64                NaN            909            909              99.6
88                NaN            909            909              99.6

In [21]:
route_master = route_state_summary.merge(delay_by_route[['Route_State', 'Delay_Rate (%)']], on='Route_State', how='left')

print(route_master.sort_values('Efficiency_Score', ascending=False).head(10))

                         Route_State  Total_Shipments  Avg_Lead_Time  \
76         Secret Factory → Nebraska                1          906.0
80       Secret Factory → New Mexico                2          906.0
121    The Other Factory → Louisiana                1          907.0
115  The Other Factory → Connecticut                2          907.5
75      Secret Factory → Mississippi                1          908.0
158          Wicked Choccy's → Maine                2          908.0
70        Secret Factory → Louisiana                2          908.5
74        Secret Factory → Minnesota                1          909.0
64         Secret Factory → Delaware                1          909.0
88   Secret Factory → South Carolina                1          909.0

     Lead_Time_StdDev  Min_Lead_Time  Max_Lead_Time  Efficiency_Score  \
76                NaN            906            906             100.0
80               2.83            904            908             100.0
121               NaN            907            907              99.9
115              2.12            906            909              99.8
75                NaN            908            908              99.7
158              0.00            908            908              99.7
70               0.71            908            909              99.7
74                NaN            909            909              99.6
64                NaN            909            909              99.6
88                NaN            909            909              99.6

     Delay_Rate (%)
76            100.0
80            100.0
121           100.0
115           100.0
75            100.0
158           100.0
70            100.0
74            100.0
64            100.0
88            100.0

In [22]:
# Flag bottlenecks: above-average lead time AND above-average volume
avg_lead_overall = route_master['Avg_Lead_Time'].mean()
avg_volume_overall = route_master['Total_Shipments'].mean()

route_master['Is_Bottleneck'] = (
    (route_master['Avg_Lead_Time'] > avg_lead_overall) &
    (route_master['Total_Shipments'] > avg_volume_overall)
)

bottlenecks = route_master[route_master['Is_Bottleneck']].sort_values('Total_Shipments', ascending=False)
print("BOTTLENECK ROUTES (slow AND high-volume):")
print(bottlenecks)

BOTTLENECK ROUTES (slow AND high-volume):
                          Route_State  Total_Shipments  Avg_Lead_Time  \
5          Lot's O' Nuts → California             1125        1316.91
144      Wicked Choccy's → California              823        1320.33
34           Lot's O' Nuts → New York              645        1330.52
189           Wicked Choccy's → Texas              388        1315.61
42       Lot's O' Nuts → Pennsylvania              331        1315.06
53         Lot's O' Nuts → Washington              269        1343.96
13           Lot's O' Nuts → Illinois              267        1319.93
38               Lot's O' Nuts → Ohio              262        1334.11
181    Wicked Choccy's → Pennsylvania              227        1339.22
193      Wicked Choccy's → Washington              221        1375.72
152        Wicked Choccy's → Illinois              210        1329.13
10            Lot's O' Nuts → Florida              209        1318.61
36     Lot's O' Nuts → North Carolina              143        1314.20
11            Lot's O' Nuts → Georgia              110        1329.56
48          Lot's O' Nuts → Tennessee              109        1390.96
141         Wicked Choccy's → Arizona              105        1322.11
6            Lot's O' Nuts → Colorado              103        1347.53
174  Wicked Choccy's → North Carolina              101        1352.76
14            Lot's O' Nuts → Indiana               90        1366.79
17           Lot's O' Nuts → Kentucky               77        1325.40
145        Wicked Choccy's → Colorado               70        1319.84
188       Wicked Choccy's → Tennessee               67        1393.76
150         Wicked Choccy's → Georgia               65        1346.15
32         Lot's O' Nuts → New Jersey               65        1335.66
21           Lot's O' Nuts → Maryland               60        1370.67
171      Wicked Choccy's → New Jersey               59        1335.39
156        Wicked Choccy's → Kentucky               58        1323.81
55          Lot's O' Nuts → Wisconsin               58        1367.64
153         Wicked Choccy's → Indiana               54        1402.46
161   Wicked Choccy's → Massachusetts               54        1334.44

     Lead_Time_StdDev  Min_Lead_Time  Max_Lead_Time  Efficiency_Score  \
5              265.37            904           1642              44.2
144            262.50            904           1642              43.7
34             249.26            904           1642              42.3
189            272.94            904           1642              44.3
42             260.48            904           1642              44.4
53             274.98            904           1642              40.5
13             268.39            906           1642              43.8
38             260.44            904           1642              41.8
181            263.67            906           1642              41.1
193            270.80            904           1642              36.2
152            266.26            906           1642              42.5
10             283.18            904           1642              43.9
36             249.31            907           1642              44.5
11             243.44            904           1642              42.5
48             257.72            906           1642              34.1
141            273.20            904           1642              43.5
6              252.65            904           1642              40.0
174            261.44            904           1642              39.3
14             236.12            907           1642              37.4
17             276.27            904           1641              43.0
145            256.20            904           1641              43.8
188            241.36            908           1641              33.7
150            251.88            904           1642              40.2
32             278.67            907           1642              41.6
21             221.92            908           1641              36.9
171            216.57            906           1642              41.7
156            269.00            904           1641              43.2
55             242.38            906           1641              37.3
153            257.77            904           1642              32.5
161            253.28            906           1642              41.8

     Delay_Rate (%)  Is_Bottleneck
5             100.0           True
144           100.0           True
34            100.0           True
189           100.0           True
42            100.0           True
53            100.0           True
13            100.0           True
38            100.0           True
181           100.0           True
193           100.0           True
152           100.0           True
10            100.0           True
36            100.0           True
11            100.0           True
48            100.0           True
141           100.0           True
6             100.0           True
174           100.0           True
14            100.0           True
17            100.0           True
145           100.0           True
188           100.0           True
150           100.0           True
32            100.0           True
21            100.0           True
171           100.0           True
156           100.0           True
55            100.0           True
153           100.0           True
161           100.0           True

In [23]:
state_summary = df.groupby('State/Province').agg(
    Total_Shipments=('Order ID', 'count'),
    Avg_Lead_Time=('Lead Time (days)', 'mean')
).reset_index()

state_summary['Avg_Lead_Time'] = state_summary['Avg_Lead_Time'].round(2)

avg_lead_state = state_summary['Avg_Lead_Time'].mean()
avg_volume_state = state_summary['Total_Shipments'].mean()

state_summary['Is_Bottleneck'] = (
    (state_summary['Avg_Lead_Time'] > avg_lead_state) &
    (state_summary['Total_Shipments'] > avg_volume_state)
)

print(state_summary[state_summary['Is_Bottleneck']].sort_values('Total_Shipments', ascending=False))

    State/Province  Total_Shipments  Avg_Lead_Time  Is_Bottleneck
55      Washington              506        1360.66           True
36  North Carolina              249        1334.88           True
11         Georgia              184        1338.64           True
50       Tennessee              183        1391.49           True
6         Colorado              182        1337.19           True

In [24]:
print("Average lead time overall:", avg_lead_overall)
print("Average volume overall:", avg_volume_overall)
print()
print(route_master[['Route_State', 'Avg_Lead_Time', 'Total_Shipments']].head(10))

Average lead time overall: 1314.0448979591838
Average volume overall: 52.01020408163265

                            Route_State  Avg_Lead_Time  Total_Shipments
0               Lot's O' Nuts → Alabama        1295.21               34
1               Lot's O' Nuts → Alberta        1273.88               16
2               Lot's O' Nuts → Arizona        1306.20              111
3              Lot's O' Nuts → Arkansas        1285.35               31
4      Lot's O' Nuts → British Columbia        1273.78               18
5            Lot's O' Nuts → California        1316.91             1125
6              Lot's O' Nuts → Colorado        1347.53              103
7           Lot's O' Nuts → Connecticut        1420.55               47
8              Lot's O' Nuts → Delaware        1273.30               43
9  Lot's O' Nuts → District of Columbia        1365.88                8

In [25]:
median_lead = route_master['Avg_Lead_Time'].median()
median_volume = route_master['Total_Shipments'].median()

route_master['Is_Bottleneck'] = (
    (route_master['Avg_Lead_Time'] > median_lead) &
    (route_master['Total_Shipments'] > median_volume)
)

bottlenecks = route_master[route_master['Is_Bottleneck']].sort_values('Total_Shipments', ascending=False)
print("Number of bottleneck routes:", len(bottlenecks))
print(bottlenecks)

Number of bottleneck routes: 52
                          Route_State  Total_Shipments  Avg_Lead_Time  \
5          Lot's O' Nuts → California             1125        1316.91
144      Wicked Choccy's → California              823        1320.33
34           Lot's O' Nuts → New York              645        1330.52
189           Wicked Choccy's → Texas              388        1315.61
42       Lot's O' Nuts → Pennsylvania              331        1315.06
53         Lot's O' Nuts → Washington              269        1343.96
13           Lot's O' Nuts → Illinois              267        1319.93
38               Lot's O' Nuts → Ohio              262        1334.11
181    Wicked Choccy's → Pennsylvania              227        1339.22
193      Wicked Choccy's → Washington              221        1375.72
152        Wicked Choccy's → Illinois              210        1329.13
10            Lot's O' Nuts → Florida              209        1318.61
36     Lot's O' Nuts → North Carolina              143        1314.20
11            Lot's O' Nuts → Georgia              110        1329.56
48          Lot's O' Nuts → Tennessee              109        1390.96
141         Wicked Choccy's → Arizona              105        1322.11
6            Lot's O' Nuts → Colorado              103        1347.53
174  Wicked Choccy's → North Carolina              101        1352.76
14            Lot's O' Nuts → Indiana               90        1366.79
17           Lot's O' Nuts → Kentucky               77        1325.40
145        Wicked Choccy's → Colorado               70        1319.84
188       Wicked Choccy's → Tennessee               67        1393.76
32         Lot's O' Nuts → New Jersey               65        1335.66
150         Wicked Choccy's → Georgia               65        1346.15
21           Lot's O' Nuts → Maryland               60        1370.67
171      Wicked Choccy's → New Jersey               59        1335.39
55          Lot's O' Nuts → Wisconsin               58        1367.64
156        Wicked Choccy's → Kentucky               58        1323.81
161   Wicked Choccy's → Massachusetts               54        1334.44
153         Wicked Choccy's → Indiana               54        1402.46
7         Lot's O' Nuts → Connecticut               47        1420.55
163       Wicked Choccy's → Minnesota               45        1330.69
180          Wicked Choccy's → Oregon               43        1316.16
24          Lot's O' Nuts → Minnesota               43        1350.40
160        Wicked Choccy's → Maryland               41        1326.71
26           Lot's O' Nuts → Missouri               36        1364.83
178        Wicked Choccy's → Oklahoma               25        1332.00
44             Lot's O' Nuts → Quebec               24        1334.12
81          Secret Factory → New York               24        1379.62
28           Lot's O' Nuts → Nebraska               23        1336.13
184    Wicked Choccy's → Rhode Island               21        1359.67
113    The Other Factory → California               21        1325.00
33         Lot's O' Nuts → New Mexico               18        1456.94
172      Wicked Choccy's → New Mexico               17        1488.88
15               Lot's O' Nuts → Iowa               16        1479.00
12              Lot's O' Nuts → Idaho               14        1351.36
154            Wicked Choccy's → Iowa               14        1403.79
128      The Other Factory → New York               14        1351.93
67          Secret Factory → Illinois               13        1328.69
94        Secret Factory → Washington               11        1472.36
170   Wicked Choccy's → New Hampshire               11        1340.09
159        Wicked Choccy's → Manitoba               10        1455.60

     Lead_Time_StdDev  Min_Lead_Time  Max_Lead_Time  Efficiency_Score  \
5              265.37            904           1642              44.2
144            262.50            904           1642              43.7
34             249.26            904           1642              42.3
189            272.94            904           1642              44.3
42             260.48            904           1642              44.4
53             274.98            904           1642              40.5
13             268.39            906           1642              43.8
38             260.44            904           1642              41.8
181            263.67            906           1642              41.1
193            270.80            904           1642              36.2
152            266.26            906           1642              42.5
10             283.18            904           1642              43.9
36             249.31            907           1642              44.5
11             243.44            904           1642              42.5
48             257.72            906           1642              34.1
141            273.20            904           1642              43.5
6              252.65            904           1642              40.0
174            261.44            904           1642              39.3
14             236.12            907           1642              37.4
17             276.27            904           1641              43.0
145            256.20            904           1641              43.8
188            241.36            908           1641              33.7
32             278.67            907           1642              41.6
150            251.88            904           1642              40.2
21             221.92            908           1641              36.9
171            216.57            906           1642              41.7
55             242.38            906           1641              37.3
156            269.00            904           1641              43.2
161            253.28            906           1642              41.8
153            257.77            904           1642              32.5
7              249.39            906           1641              30.1
163            310.76            906           1642              42.3
180            242.41            906           1642              44.3
24             282.63            906           1642              39.6
160            264.94            908           1642              42.8
26             267.22            907           1640              37.7
178            250.49            909           1642              42.1
44             298.55            904           1642              41.8
81             274.43            905           1641              35.6
28             237.68            905           1639              41.6
184            280.10            906           1640              38.4
113            265.13            908           1640              43.1
33             258.26            909           1642              25.1
172            226.43            909           1641              20.8
15             187.51           1270           1641              22.1
12             255.75            908           1641              39.5
154            272.00            909           1641              32.4
128            326.82            906           1641              39.4
67             360.03            907           1641              42.6
94             190.50           1270           1641              23.0
170            275.30            906           1641              41.0
159            192.90           1271           1639              25.3

     Delay_Rate (%)  Is_Bottleneck
5             100.0           True
144           100.0           True
34            100.0           True
189           100.0           True
42            100.0           True
53            100.0           True
13            100.0           True
38            100.0           True
181           100.0           True
193           100.0           True
152           100.0           True
10            100.0           True
36            100.0           True
11            100.0           True
48            100.0           True
141           100.0           True
6             100.0           True
174           100.0           True
14            100.0           True
17            100.0           True
145           100.0           True
188           100.0           True
32            100.0           True
150           100.0           True
21            100.0           True
171           100.0           True
55            100.0           True
156           100.0           True
161           100.0           True
153           100.0           True
7             100.0           True
163           100.0           True
180           100.0           True
24            100.0           True
160           100.0           True
26            100.0           True
178           100.0           True
44            100.0           True
81            100.0           True
28            100.0           True
184           100.0           True
113           100.0           True
33            100.0           True
172           100.0           True
15            100.0           True
12            100.0           True
154           100.0           True
128           100.0           True
67            100.0           True
94            100.0           True
170           100.0           True
159           100.0           True

In [26]:
median_lead_state = state_summary['Avg_Lead_Time'].median()
median_volume_state = state_summary['Total_Shipments'].median()

state_summary['Is_Bottleneck'] = (
    (state_summary['Avg_Lead_Time'] > median_lead_state) &
    (state_summary['Total_Shipments'] > median_volume_state)
)

print("Number of bottleneck states:", len(state_summary[state_summary['Is_Bottleneck']]))
print(state_summary[state_summary['Is_Bottleneck']].sort_values('Total_Shipments', ascending=False))

Number of bottleneck states: 17
    State/Province  Total_Shipments  Avg_Lead_Time  Is_Bottleneck
34        New York             1128        1324.49           True
43    Pennsylvania              587        1324.20           True
55      Washington              506        1360.66           True
13        Illinois              492        1323.15           True
39            Ohio              469        1325.73           True
36  North Carolina              249        1334.88           True
11         Georgia              184        1338.64           True
50       Tennessee              183        1391.49           True
6         Colorado              182        1337.19           True
14         Indiana              149        1381.50           True
17        Kentucky              139        1328.45           True
32      New Jersey              130        1338.33           True
57       Wisconsin              110        1343.00           True
21        Maryland              105        1356.78           True
24       Minnesota               89        1335.47           True
7      Connecticut               82        1357.55           True
26        Missouri               66        1339.86           True

In [27]:
factory_coords = pd.DataFrame({
    'Factory': ["Lot's O' Nuts", "Wicked Choccy's", "Sugar Shack", "Secret Factory", "The Other Factory"],
    'Latitude': [32.881893, 32.076176, 48.11914, 41.446333, 35.1175],
    'Longitude': [-111.768036, -81.088371, -96.18115, -90.565487, -89.971107]
})

print(factory_coords)

             Factory   Latitude   Longitude
0      Lot's O' Nuts  32.881893 -111.768036
1    Wicked Choccy's  32.076176  -81.088371
2        Sugar Shack  48.119140  -96.181150
3     Secret Factory  41.446333  -90.565487
4  The Other Factory  35.117500  -89.971107

In [28]:
state_coords = {
    'Alabama': (32.806671, -86.791130), 'Alaska': (61.370716, -152.404419),
    'Arizona': (33.729759, -111.431221), 'Arkansas': (34.969704, -92.373123),
    'California': (36.116203, -119.681564), 'Colorado': (39.059811, -105.311104),
    'Connecticut': (41.597782, -72.755371), 'Delaware': (39.318523, -75.507141),
    'Florida': (27.766279, -81.686783), 'Georgia': (33.040619, -83.643074),
    'Hawaii': (21.094318, -157.498337), 'Idaho': (44.240459, -114.478828),
    'Illinois': (40.349457, -88.986137), 'Indiana': (39.849426, -86.258278),
    'Iowa': (42.011539, -93.210526), 'Kansas': (38.526600, -96.726486),
    'Kentucky': (37.668140, -84.670067), 'Louisiana': (31.169546, -91.867805),
    'Maine': (44.693947, -69.381927), 'Maryland': (39.063946, -76.802101),
    'Massachusetts': (42.230171, -71.530106), 'Michigan': (43.326618, -84.536095),
    'Minnesota': (45.694454, -93.900192), 'Mississippi': (32.741646, -89.678696),
    'Missouri': (38.456085, -92.288368), 'Montana': (46.921925, -110.454353),
    'Nebraska': (41.125370, -98.268082), 'Nevada': (38.313515, -117.055374),
    'New Hampshire': (43.452492, -71.563896), 'New Jersey': (40.298904, -74.521011),
    'New Mexico': (34.840515, -106.248482), 'New York': (42.165726, -74.948051),
    'North Carolina': (35.630066, -79.806419), 'North Dakota': (47.528912, -99.784012),
    'Ohio': (40.388783, -82.764915), 'Oklahoma': (35.565342, -96.928917),
    'Oregon': (44.572021, -122.070938), 'Pennsylvania': (40.590752, -77.209755),
    'Rhode Island': (41.680893, -71.511780), 'South Carolina': (33.856892, -80.945007),
    'South Dakota': (44.299782, -99.438828), 'Tennessee': (35.747845, -86.692345),
    'Texas': (31.054487, -97.563461), 'Utah': (40.150032, -111.862434),
    'Vermont': (44.045876, -72.710686), 'Virginia': (37.769337, -78.169968),
    'Washington': (47.400902, -121.490494), 'West Virginia': (38.491226, -80.954456),
    'Wisconsin': (44.268543, -89.616508), 'Wyoming': (42.755966, -107.302490)
}

df['Cust_Lat'] = df['State/Province'].map(lambda x: state_coords.get(x, (None, None))[0])
df['Cust_Lon'] = df['State/Province'].map(lambda x: state_coords.get(x, (None, None))[1])

print("States not matched (should be empty or very few):")
print(df[df['Cust_Lat'].isnull()]['State/Province'].unique())

States not matched (should be empty or very few):
['Ontario' 'Alberta' 'British Columbia' 'Quebec' 'Nova Scotia'
 'Newfoundland and Labrador' 'New Brunswick' 'Prince Edward Island'
 'District of Columbia' 'Manitoba' 'Saskatchewan']

In [29]:
state_summary_map = df.groupby('State/Province').agg(
    Avg_Lead_Time=('Lead Time (days)', 'mean'),
    Total_Shipments=('Order ID', 'count'),
    Lat=('Cust_Lat', 'first'),
    Lon=('Cust_Lon', 'first')
).reset_index()

state_summary_map['Avg_Lead_Time'] = state_summary_map['Avg_Lead_Time'].round(2)

fig = px.scatter_geo(
    state_summary_map,
    lat='Lat', lon='Lon',
    size='Total_Shipments',
    color='Avg_Lead_Time',
    color_continuous_scale='RdYlGn_r',  # Red = slow, Green = fast
    hover_name='State/Province',
    hover_data=['Avg_Lead_Time', 'Total_Shipments'],
    scope='usa',
    title='Average Shipping Lead Time by State'
)
fig.show()

In [30]:
import plotly.graph_objects as go

fig2 = px.scatter_geo(
    state_summary_map,
    lat='Lat', lon='Lon',
    size='Total_Shipments',
    color='Avg_Lead_Time',
    color_continuous_scale='RdYlGn_r',
    hover_name='State/Province',
    hover_data=['Avg_Lead_Time', 'Total_Shipments'],
    scope='usa',
    title='Shipping Network: Factories and Customer Lead Times'
)

fig2.add_trace(go.Scattergeo(
    lat=factory_coords['Latitude'],
    lon=factory_coords['Longitude'],
    text=factory_coords['Factory'],
    mode='markers+text',
    marker=dict(size=14, color='black', symbol='star'),
    textposition='top center',
    name='Factories'
))

fig2.show()

In [31]:
with pd.ExcelWriter('Nassau_Candy_Route_Analysis.xlsx') as writer:
    route_master.to_excel(writer, sheet_name='Route Efficiency', index=False)
    route_region_summary.to_excel(writer, sheet_name='Region Summary', index=False)
    shipmode_summary.to_excel(writer, sheet_name='Ship Mode Comparison', index=False)
    state_summary_map.to_excel(writer, sheet_name='State Summary', index=False)
    bottlenecks.to_excel(writer, sheet_name='Bottleneck Routes', index=False)

print("Saved! Check the Files panel.")

Saved! Check the Files panel.

In [32]:
df.to_csv('cleaned_shipment_data.csv', index=False)
route_master.to_csv('route_master.csv', index=False)

print("Saved cleaned data files for the Streamlit app!")

Saved cleaned data files for the Streamlit app!

In [33]:
%%writefile app.py
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

st.set_page_config(page_title="Nassau Candy Route Efficiency", page_icon="🍬", layout="wide")

# ── Custom styling ──────────────────────────────────────────
st.markdown("""
<style>
    h1 { color: #7B2D8E; font-weight: 700; }
    .metric-box {
        background: linear-gradient(135deg, #7B2D8E 0%, #B83280 100%);
        padding: 20px; border-radius: 12px; color: white; text-align: center;
    }
    .metric-box h2 { color: white; margin: 0; font-size: 32px; }
    .metric-box p { color: #F0D9E8; margin: 4px 0 0; font-size: 13px; }
</style>
""", unsafe_allow_html=True)

# ── Load data ────────────────────────────────────────────────
@st.cache_data
def load_data():
    df = pd.read_csv('cleaned_shipment_data.csv')
    df['Order Date'] = pd.to_datetime(df['Order Date'])
    df['Ship Date'] = pd.to_datetime(df['Ship Date'])
    route_master = pd.read_csv('route_master.csv')
    return df, route_master

df, route_master = load_data()

factory_coords = pd.DataFrame({
    'Factory': ["Lot's O' Nuts", "Wicked Choccy's", "Sugar Shack", "Secret Factory", "The Other Factory"],
    'Latitude': [32.881893, 32.076176, 48.11914, 41.446333, 35.1175],
    'Longitude': [-111.768036, -81.088371, -96.18115, -90.565487, -89.971107]
})

st.title("🍬 Nassau Candy Distributor — Shipping Route Efficiency")
st.caption("Factory-to-customer logistics intelligence dashboard")

# ── Sidebar filters ──────────────────────────────────────────
st.sidebar.header("Filters")

min_date = df['Order Date'].min()
max_date = df['Order Date'].max()
date_range = st.sidebar.date_input("Order Date Range", [min_date, max_date])

regions = st.sidebar.multiselect("Region", options=sorted(df['Region'].unique()), default=sorted(df['Region'].unique()))
ship_modes = st.sidebar.multiselect("Ship Mode", options=sorted(df['Ship Mode'].unique()), default=sorted(df['Ship Mode'].unique()))
lead_time_threshold = st.sidebar.slider("Lead Time Threshold (days)", 0, int(df['Lead Time (days)'].max()), 7)

# ── Apply filters ────────────────────────────────────────────
mask = (
    (df['Order Date'] >= pd.to_datetime(date_range[0])) &
    (df['Order Date'] <= pd.to_datetime(date_range[1])) &
    (df['Region'].isin(regions)) &
    (df['Ship Mode'].isin(ship_modes))
)
filtered = df[mask]

# ── Top KPI row ──────────────────────────────────────────────
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.markdown(f'<div class="metric-box"><p>TOTAL SHIPMENTS</p><h2>{len(filtered):,}</h2></div>', unsafe_allow_html=True)
with col2:
    avg_lead = filtered['Lead Time (days)'].mean()
    st.markdown(f'<div class="metric-box"><p>AVG LEAD TIME</p><h2>{avg_lead:.1f} days</h2></div>', unsafe_allow_html=True)
with col3:
    delayed_pct = (filtered['Lead Time (days)'] > lead_time_threshold).mean() * 100
    st.markdown(f'<div class="metric-box"><p>DELAYED SHIPMENTS</p><h2>{delayed_pct:.1f}%</h2></div>', unsafe_allow_html=True)
with col4:
    st.markdown(f'<div class="metric-box"><p>ACTIVE ROUTES</p><h2>{filtered["Route_State"].nunique()}</h2></div>', unsafe_allow_html=True)

st.divider()

# ── Module 1: Route Efficiency Overview ──────────────────────
st.subheader("📊 Route Efficiency Overview")
tab1, tab2 = st.tabs(["Top 10 Most Efficient", "Bottom 10 Least Efficient"])
with tab1:
    top10 = route_master.sort_values('Efficiency_Score', ascending=False).head(10)
    st.dataframe(top10[['Route_State', 'Avg_Lead_Time', 'Total_Shipments', 'Efficiency_Score']], use_container_width=True)
with tab2:
    bottom10 = route_master.sort_values('Efficiency_Score', ascending=True).head(10)
    st.dataframe(bottom10[['Route_State', 'Avg_Lead_Time', 'Total_Shipments', 'Efficiency_Score']], use_container_width=True)

st.divider()

# ── Module 2: Geographic Shipping Map ────────────────────────
st.subheader("🗺️ Geographic Shipping Map")
state_geo = filtered.groupby('State/Province').agg(
    Avg_Lead_Time=('Lead Time (days)', 'mean'),
    Total_Shipments=('Order ID', 'count'),
    Lat=('Cust_Lat', 'first'),
    Lon=('Cust_Lon', 'first')
).reset_index()

fig_map = px.scatter_geo(
    state_geo, lat='Lat', lon='Lon', size='Total_Shipments', color='Avg_Lead_Time',
    color_continuous_scale='RdYlGn_r', hover_name='State/Province',
    hover_data=['Avg_Lead_Time', 'Total_Shipments'], scope='usa'
)
fig_map.add_trace(go.Scattergeo(
    lat=factory_coords['Latitude'], lon=factory_coords['Longitude'],
    text=factory_coords['Factory'], mode='markers+text',
    marker=dict(size=14, color='black', symbol='star'), textposition='top center', name='Factories'
))
st.plotly_chart(fig_map, use_container_width=True)

st.divider()

# ── Module 3: Ship Mode Comparison ───────────────────────────
st.subheader("🚚 Ship Mode Comparison")
shipmode_compare = filtered.groupby('Ship Mode').agg(
    Avg_Lead_Time=('Lead Time (days)', 'mean'),
    Total_Shipments=('Order ID', 'count')
).reset_index()
fig_ship = px.bar(shipmode_compare, x='Ship Mode', y='Avg_Lead_Time', color='Ship Mode',
                   text_auto='.1f', title='Average Lead Time by Ship Mode')
st.plotly_chart(fig_ship, use_container_width=True)

st.divider()

# ── Module 4: Route Drill-Down ───────────────────────────────
st.subheader("🔍 Route Drill-Down")
selected_state = st.selectbox("Select a State to Drill Down", sorted(filtered['State/Province'].unique()))
state_detail = filtered[filtered['State/Province'] == selected_state]
st.write(f"**{len(state_detail)} shipments** to {selected_state}")
st.dataframe(
    state_detail[['Order ID', 'Order Date', 'Ship Date', 'Lead Time (days)', 'Ship Mode', 'Factory']].sort_values('Order Date'),
    use_container_width=True
)

Writing app.py

In [34]:
!streamlit run app.py &>/content/logs.txt &
!npx --yes localtunnel --port 8501

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼your url is: https://silent-boats-stare.loca.lt
^C

In [35]:
import os
print(os.listdir('/content'))

['.config', 'Nassau_Candy_Route_Analysis.xlsx', 'Nassau Candy Distributor.csv', 'app.py', 'route_master.csv', 'logs.txt', 'cleaned_shipment_data.csv', 'sample_data']

In [36]:
!cat /content/logs.txt

/bin/bash: line 1: streamlit: command not found

In [37]:
!pip install streamlit --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 90.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 107.1 MB/s eta 0:00:00

In [ ]:
!streamlit run app.py &>/content/logs.txt &
!npx --yes localtunnel --port 8501

⠙⠹⠸⠼⠴⠦your url is: https://icy-jars-prove.loca.lt